Upgrade template.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -4,10 +4,43 @@
 
 # Parse cmd arguments
 
-SRC_BRANCH="main"
+SRC_BRANCH="master"
 DEPLOY_BRANCH="gh-pages"
 
-USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH]"
+USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH] [--verbose] [--no-push]"
+
+while [[ $# > 0 ]]; do
+    key="$1"
+
+    case $key in
+        -h|--help)
+        echo $USAGE_MSG
+        exit 0
+        ;;
+        -u|--user)
+        ;;
+        -s|--src)
+        SRC_BRANCH="$2"
+        shift
+        ;;
+        -d|--deploy)
+        DEPLOY_BRANCH="$2"
+        shift
+        ;;
+        --verbose)
+        set -x
+        ;;
+        --no-push)
+        NO_PUSH="--no-push"
+        ;;
+        *)
+        echo "Option $1 is unknown." >&2
+        echo $USAGE_MSG >&2
+        exit 1
+        ;;
+    esac
+    shift
+done
 
 # Exit if any subcommand fails
 set -e
@@ -32,6 +65,15 @@ if ! git diff-index --quiet HEAD --; then
     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
+# Check if there are any untracked files
+if ! test -z "$(git ls-files --exclude-standard --others)"; then
+    echo "There are untracked files:"
+    git ls-files --exclude-standard --others
+    echo "Please commit those files or stash them before proceeding."
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
+
 # Switch to source branch (creates it if necessary from the current branch)
 if [ `git branch | grep $SRC_BRANCH | tr ' ' '\n' | tail -1` ]
 then
@@ -47,18 +89,27 @@ then
 fi
 git checkout -b $DEPLOY_BRANCH
 
+# Export JEKYLL_ENV=production
+export JEKYLL_ENV=production
+
 # Build site
-bundle exec jekyll build
+bundle exec jekyll build --lsi
+
+# Purge unused css
+purgecss -c purgecss.config.js
 
 # Delete and move files
 find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name 'CNAME' ! -name '.gitignore' -exec rm -rf {} \;
 mv _site/* .
 rm -R _site/
 
+# Create `.nojekyll` file (bypass GitHub Pages Jekyll processing)
+touch .nojekyll
+
 # Push to DEPLOY_BRANCH
 git add -fA
 git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
-git push -f -q origin $DEPLOY_BRANCH
+[[ ${NO_PUSH} ]] || git push -f -q origin $DEPLOY_BRANCH
 
 # Move back to SRC_BRANCH
 git checkout $SRC_BRANCH
